import numpy as np

class SpeechBuffer:
    """
    A rolling speech buffer that accumulates only audio chunks containing speech.
    It extracts overlapping windows of a fixed duration.
    """
    def __init__(self, window_seconds: int = 4, stride_seconds: int = 1, sample_rate: int = 16000):
        self.window_seconds = window_seconds
        self.stride_seconds = stride_seconds
        self.sample_rate = sample_rate
        
        self.window_samples = int(window_seconds * sample_rate)
        self.stride_samples = int(stride_seconds * sample_rate)
        
        # Internal accumulator of voiced audio
        self.accumulator = np.array([], dtype=np.float32)
        
    def push_and_extract_windows(self, audio_chunk: np.ndarray) -> list[np.ndarray]:
        """
        Pushes new speech audio into the buffer and returns any complete 
        windows generated by sliding the stride over the accumulator.
        """
        if len(audio_chunk) > 0:
            self.accumulator = np.concatenate((self.accumulator, audio_chunk))
            
        windows = []
        
        # Extract full windows
        while len(self.accumulator) >= self.window_samples:
            window = self.accumulator[:self.window_samples].copy()
            windows.append(window)
            
            # Slide forward by stride
            self.accumulator = self.accumulator[self.stride_samples:]
            
        return windows

    def clear(self):
        """Clears the buffer."""
        self.accumulator = np.array([], dtype=np.float32)
