"""Add protected_numbers table

Revision ID: 29f50e1e12e4
Revises: 5b380ad82e97
Create Date: 2026-09-23 01:20:39.638542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f50e1e12e4'
down_revision: Union[str, Sequence[str], None] = '5b380ad82e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protected_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_number', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protected_numbers_provider_number'), 'protected_numbers', ['provider_number'], unique=False)
    op.create_index(op.f('ix_protected_numbers_user_id'), 'protected_numbers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protected_numbers_user_id'), table_name='protected_numbers')
    op.drop_index(op.f('ix_protected_numbers_provider_number'), table_name='protected_numbers')
    op.drop_table('protected_numbers')
    # ### end Alembic commands ###
