"""Add trusted voices and embeddings

Revision ID: 5b380ad82e97
Revises: 575ee2a8c28d
Create Date: 2026-09-23 00:57:03.892776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b380ad82e97'
down_revision: Union[str, Sequence[str], None] = '575ee2a8c28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_voices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_voices_user_id'), 'trusted_voices', ['user_id'], unique=False)
    op.create_table('voice_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trusted_voice_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trusted_voice_id'], ['trusted_voices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_embeddings_trusted_voice_id'), 'voice_embeddings', ['trusted_voice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_embeddings_trusted_voice_id'), table_name='voice_embeddings')
    op.drop_table('voice_embeddings')
    op.drop_index(op.f('ix_trusted_voices_user_id'), table_name='trusted_voices')
    op.drop_table('trusted_voices')
    # ### end Alembic commands ###
