import numpy as np

class WindowManager:
    def __init__(self, window_seconds: float = 3.0, stride_seconds: float = 1.0, sample_rate: int = 16000):
        self.window_seconds = window_seconds
        self.stride_seconds = stride_seconds
        self.sample_rate = sample_rate
        
        self.window_samples = int(self.window_seconds * self.sample_rate)
        self.stride_samples = int(self.stride_seconds * self.sample_rate)
        
        # Internal accumulator for precise sliding window logic
        self.accumulator = np.array([], dtype=np.int16)
        
    def push_and_extract_windows(self, audio: np.ndarray) -> list[np.ndarray]:
        """
        Pushes new audio and returns any complete 3-second windows 
        generated by sliding the 1-second stride over the accumulator.
        """
        self.accumulator = np.concatenate((self.accumulator, audio))
        windows = []
        
        # While we have at least one full window
        while len(self.accumulator) >= self.window_samples:
            # Extract the window
            window = self.accumulator[:self.window_samples].copy()
            windows.append(window)
            
            # Slide forward by stride
            self.accumulator = self.accumulator[self.stride_samples:]
            
        return windows

    def clear(self):
        self.accumulator = np.array([], dtype=np.int16)
